name: Verify jalien-setup
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag'     
        required: false
        default: 'latest'
      source_jalien_repo:
        description: 'Source JAliEn Repo'     
        required: false
        default: 'https://gitlab.cern.ch/jalien/jalien'
      source_jalien_branch:
        description: 'Source JAliEn Repo Branch'     
        required: false
        default: 'master'

# run-name: ${{ github.event_name == 'workflow_dispatch' && format('Test Pipeline- Tag:{0}, Branch:{1}', tojson(inputs.tag), github.ref_name) || '' }}
# run-name: ${{ github.event_name == 'workflow_dispatch' }} && format('Commit- {0} Tag:{1}, Branch:{2}', ${{ github.event.head_commit.message }}, tojson(inputs.image_tag), github.ref_name) || '' }}
run-name: ${{ github.event_name == 'workflow_dispatch' && format('Tag:{0}, Branch:{1}', ${{ github.event.inputs.image_tag }}, github.ref_name) || '' }}

jobs:
  test-jalien-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Clone jalien-setup
        run: |
          cd ${{ github.workspace }}
          cd ..
          git clone https://gitlab.cern.ch/jalien/jalien-setup
          cd ./jalien-setup && git checkout origin/updated-sql8-setup
      - name: Clone jalien
        run: |
          cd ${{ github.workspace }}
          cd ..
          git clone ${{ github.event.inputs.source_jalien_repo }}
          cd ./jalien && git checkout origin/${{ github.event.inputs.source_jalien_branch }}
      - name: debug
        run: cat ${{ github.workspace }}/../jalien-setup/bash/tasks/create_shared.sh
      - name: Create config.sh for bash
        run: |
          cd ${{ github.workspace }}
          cd ..
          echo "
          export BASE_DIR=$(pwd)
          export SCRIPT_DIR=$(pwd)/jalien-setup/bash
          export SHARED_VOLUME=$(pwd)/SHARED_VOLUME
          export JALIEN=$(pwd)/jalien
          export JALIEN_SETUP=$(pwd)/jalien-setup
          export JALIEN_SOURCE=${{ github.event.inputs.source_jalien_repo }}
          export JALIEN_SETUP_SOURCE=https://github.com/FYP-Jalien/jalien-setup
          export CE_NAME=shared_volume_JCentral-dev-CE_1
          export JCENTRAL_NAME=shared_volume_JCentral-dev_1
          export SCHEDD_NAME=shared_volume_schedd_1
          export SE_NAME=shared_volume_JCentral-dev-SE_1
          export WORKER_NAME=shared_volume_worker1_1
          " >> ${{ github.workspace }}/../jalien-setup/bash/config/config.sh  
      
      - name: Run jalien-setup bash scripts
        run: |
          cd ${{ github.workspace }}/../jalien-setup/bash
          ./start.sh --shared --${{ github.event.inputs.image_tag }}
      - name: Clone test-suite
        run: |
          cd ${{ github.workspace }}
          cd ..
          git clone https://gitlab.cern.ch/jalien/test-suite
      - name: Create .env for test-suite
        run: |
          cd ${{ github.workspace }}
          cd ..
          echo "
          export SHARED_VOLUME_PATH=$(pwd)/SHARED_VOLUME
          export JALIEN_SETUP_PATH=$(pwd)/jalien-setup
          export CONTAINER_NAME_CE=shared_volume_JCentral-dev-CE_1
          export CONTAINER_NAME_CENTRAL=shared_volume_JCentral-dev_1
          export CONTAINER_NAME_SCHEDD=shared_volume_schedd_1
          export CONTAINER_NAME_SE=shared_volume_JCentral-dev-SE_1
          export CONTAINER_NAME_WORKER=shared_volume_worker1_1
          export SCRIPT_DIR=$(pwd)/test-suite
          export ALIENV_PATH=$(pwd)/test-suite/files/alma-alienv
          export SAMPLE_JDL_PATH=$(pwd)/test-suite/files/sample_test.jdl
          export TESTSCRIPT_PATH=$(pwd)/test-suite/files/testscript_test.sh
          " >> ${{ github.workspace }}/../test-suite/.env   
      - name: Run test-suite for container specific tests
        run: |
          cd ${{ github.workspace }}/../test-suite
          ./index.sh --container-only --${{ github.event.inputs.image_tag }}